version: '3.9'

services:
  redis:
    image: redis:latest
    networks:
      - webnet

  db:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_USER: 
      POSTGRES_DB: 
    volumes:
          
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - webnet
    environment:
      DATABASE_URL: 
      REDIS_URL: redis://redis:6379

networks:
  webnet:

volumes:
  postgres_data:

